# Доступ только Authorized Required, @ auth_required
GET http://127.0.0.1:10001/genres/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM
###

# Доступ только Authorized Required, @ auth_required
# Доступ только Role admin Required, @ admin_required
POST http://127.0.0.1:10001/genres/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM

{
  "id": 19,
  "name": "Документальный"
}

###

# Доступ только Authorized Required, @ auth_required
GET http://127.0.0.1:10001/genres/10
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM

###

# Доступ только Authorized Required, @ auth_required
# Доступ только Role admin Required, @ admin_required
PUT http://127.0.0.1:10001/genres/19
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM

{
  "id": 19,
  "name": "Мюзикл"
}

###

# Доступ только Authorized Required, @ auth_required
# Доступ только Role admin Required, @ admin_required
DELETE http://127.0.0.1:10001/genres/19
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzOFx1MDQzYVx1MDQ0Mlx1MDQzZVx1MDQ0MCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3MDE3OTMzfQ.bRkNJcnfFW6RtTbiRxaK1Vtc0VN47Rx7wn6msIeWBdM
